# Generated by Django 3.2.5 on 2021-07-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_produto',
            new_name='preco_marketing',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco_produto_promocional',
            new_name='preco_marketing_promocional',
        ),
    ]
