# Generated by Django 3.2.5 on 2021-07-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20210707_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variacao',
        ),
    ]
