# Generated by Django 3.2.5 on 2021-07-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_variacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
