# Generated by Django 3.2.5 on 2021-07-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_variacao_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='preco_marketing',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco_promocional',
            new_name='preco_marketing_promocional',
        ),
        migrations.RenameField(
            model_name='variacao',
            old_name='preco_variacao',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='variacao',
            old_name='preco_variacao_promocional',
            new_name='preco_promocional',
        ),
    ]
