# Generated by Django 3.2.5 on 2021-07-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_auto_20210707_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing_promocional',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
